Add tag support
rohanchandra/type-theme pull request #48
Opened 2017-06-16 20:01 UTC by divayprakash

Closes #32

2017-06-16 20:09 UTC, divayprakash commented
![Markdown and HTML](http://res.cloudinary.com/divayprakash/image/upload/v1497643693/1_brc8pa.png)

2017-06-16 20:10 UTC, divayprakash commented
![Feature Images](http://res.cloudinary.com/divayprakash/image/upload/v1497643690/2_kqplm6.png)

2017-06-16 20:10 UTC, divayprakash commented
![Tags Page](http://res.cloudinary.com/divayprakash/image/upload/v1497643689/3_yuuphg.png)

2017-06-16 20:20 UTC, divayprakash commented
Tags can be added by simply following the Jekyll front-matter convention and adding `tags: [comma separated tags, comma separated tags]` to the post's front matter.

I used the same theme styles as the `a` element styled with the `button` class (ie. `<a class="button" ...>`) to display a list of tags under a post title/feature image. The tags page is similar to the index page in terms of styling. Thus no styles were added/changed for this feature.

@rohanchandra 
* Just something to think about, should I also display the post tags on the `index.html` page in the same location ie. under the post title? I haven't implemented that as of now.
* Also, I am going to add a parameter to `_config.yml` to enable/disable the tags feature.
* I am working on updating the docs for this feature.

2017-06-17 11:26 UTC, rohanchandra requested changes
Hey @divayprakash, this is awesome!

Just some tweaks to the design and markup:

1. Move tags to below the content into the`footer` of the `article`.
2. In terms of design, it'll be best to match the header meta design with the center alignment + text styled with the `.meta` class (see below)
<img width="1213" alt="screenshot" src="https://user-images.githubusercontent.com/816965/27252431-ba11688e-53a1-11e7-91b0-13e4bc871e0c.png">
3. Can we make the tags page use a design that's consistent with the index page:
<img width="504" alt="tags" src="https://user-images.githubusercontent.com/816965/27252480-fea15cb0-53a2-11e7-8a17-f9c55e6973ea.png">

> Just something to think about, should I also display the post tags on the index.html page in the same location ie. under the post title? I haven't implemented that as of now.

I think it's best to keep the index free of the tags, as the index in this theme is intended as more of a summary.

> Should I hide the tags page from appearing in the header's navigation bar?

Yes, hide the tags page link by default, we can explain in the docs how to add a nav link to the tags page, if users want to include a link to the page (or otherwise include it as an option)

> The type-theme docs would need to be updated for this feature. I understand the change would need to be made to this file. How should we proceed with that?

Yep, please fork the repo at https://github.com/rohanchandra/rohanchandra.github.io/ to add your documentation changes 👍 Feel free to make a new heading for tags which includes information the user would need to use this feature (i.e. adding tags to a post, adding an optional navigation link to tags page and disabling the feature).

Thanks for this pull request!

2017-06-17 11:26 UTC, rohanchandra commented on _layouts/post.html
> +    {% for tag in page.tags %}
Tags would be best placed in a new `<footer>` HTML element inside the `<article>` below the post content, rather than within the post content (`.post-content`)

2017-06-17 21:06 UTC, divayprakash commented
@rohanchandra I'll make the changes as you said but it might take a couple of days, just a bit busy over the weekend.

2017-06-18 21:33 UTC, divayprakash commented
@rohanchandra 
* `index.html` is free of tags.
* Tags page is removed from the header's navigation bar by default.
* Tags page styling is more consistent with the index page.
* I've moved the tags on the post pages to a `<footer>` element at the end of the `<article>` element after the `post-content` div.
* Tags are now centered and styled using the `meta` class.

For more please see screenshots below.

2017-06-18 21:33 UTC, divayprakash commented
![tags](https://user-images.githubusercontent.com/11337492/27264436-eb2b8c06-549b-11e7-82ab-91c8da94bd55.png)

2017-06-18 21:34 UTC, divayprakash commented
![feature](https://user-images.githubusercontent.com/11337492/27264437-fc1c5978-549b-11e7-91aa-f40e61565cc4.png)
![markdown](https://user-images.githubusercontent.com/11337492/27264438-fe96e68c-549b-11e7-8eb1-a82f80c76e37.png)

2017-06-18 21:36 UTC, divayprakash commented
In styling the tags page to resemble the index page, I find that the tag names and the post title under that tag are too close in size and difficult to distinguish. An alternate to this could be styling the tag names in the `$link-color` as below -
![tags_alt](https://user-images.githubusercontent.com/11337492/27264448-4ed74a56-549c-11e7-9c53-d43b1cbdaf47.png)

2017-06-19 00:28 UTC, rohanchandra approved these changes

2017-06-19 00:59 UTC, rohanchandra commented
Looks great! Just two final changes: :

1. Reuse the existing `.meta` class instead of copying the CSS declarations from `.meta`
2. Make the `margin-right` on the `tags.html` consistent with the post button margin

> In styling the tags page to resemble the index page, I find that the tag names and the post title under that tag are too close in size and difficult to distinguish. An alternate to this could be styling the tag names in the $link-color as below

Try setting the `margin-bottom` of `h1` on the tags page to `0`, should help a bit with the visual grouping (see screenshot).

I want to reserve `$link-color` for links, so if you want to add `$link-color` to the `h1`, you'll have to make it an in-page link. e.g. clicking the 'feature-image' heading link would link to `./tags#feature-image`

![](https://user-images.githubusercontent.com/816965/27265767-8e15e6be-54dd-11e7-80b5-2a2446e92860.png)

2017-06-19 01:00 UTC, rohanchandra reviewed
Comments attached. Thanks!

2017-06-19 01:00 UTC, rohanchandra commented on _sass/layouts/_posts.scss
> +  .meta {
The `.meta` rule shouldn't be copied and pasted. Can we refactor the `.meta` rule used in the `header` instead.

2017-06-19 01:00 UTC, rohanchandra commented on _sass/layouts/_tags.scss
> +  .meta {
Reuse the existing `.meta` class styling

2017-06-19 01:00 UTC, rohanchandra commented on tags.html
> +      <a class="button" href="#{{ this_word | cgi_escape }}">
Button margin isn't consistent with that on the post pages. Please make this `tags.html` page have the same `margin-right` on the buttons as the post pages.

2017-06-19 07:58 UTC, divayprakash commented
> Try setting the `margin-bottom` of `h1` on the tags page to `0`, should help a bit with the visual grouping (see screenshot).
> I want to keep `$link-color` for links, so if you want to add `$link-color` to the `h1`, I think it would be best to make the heading an in-page link. e.g. clicking the 'feature-image' heading link would link to `./tags#feature-image`

Done in 5cd1902.

2017-06-19 08:04 UTC, divayprakash commented
> Reuse the existing .meta class instead of copying the CSS declarations from .meta

Done in 4adf5c8.

2017-06-19 08:25 UTC, divayprakash commented
> Make the `margin-right` on the `tags.html` consistent with the post button margin.

Done in de0ad37.

2017-06-19 16:40 UTC, divayprakash commented
This is the final `tags.html`
![1](https://user-images.githubusercontent.com/11337492/27295861-0dbf35b0-553c-11e7-8337-a69dff2f3243.png)

2017-06-19 19:58 UTC, divayprakash commented
@rohanchandra Hey! I'm still making a few changes so just wait until I update this regarding the same. Thanks!

2017-06-19 20:44 UTC, divayprakash commented
So I think this is done now, just finished up adding some liquid to the posts template to render tag/tags depending on number of tags and also to not render the `footer` element containing tags in case the post does not have tags.

I'd love to hear your thought on this, so please let me know! And if you can think of anything else we can add on then I can work that out too.

2017-06-20 04:13 UTC, rohanchandra commented
Great work @divayprakash, this looks really good. Can you update the docs for this feature? I'm thinking info on how to add tags to a post / optional navigation link to tags page (or use of `tags.html`) and disabling the feature would be good to have.

I'll test out your branch for testing and then merge it in after this 👍

2017-06-20 07:30 UTC, divayprakash commented
@rohanchandra I'm using this theme for my blog so I've added category support too in the same manner as tags. The equivalent page for listing the various categories and the posts under them is `categories.html` and looks the same as `tags.html`. The categories for a post are also rendered in a `footer` element and look the same as the existing tags implementation. Should I add the same to this PR?

2017-06-20 07:40 UTC, rohanchandra commented
@divayprakash What's the difference between a category and tag?

2017-06-20 07:50 UTC, divayprakash commented
* Tags don't change the post url in any manner. However a post in the categories 'general, code' will have the URL `/general/code/2017/06/20/foo-bar.html`
* Permalinks don't support tags but do support categories (Source : [StackOverflow](https://stackoverflow.com/questions/8675841/whats-the-difference-between-categories-and-tags-in-jekyll#comment30175839_8710254))

2017-06-20 07:51 UTC, divayprakash commented
As the categories change the post url, they provide an easy way to organise posts into folders depending on content or whatever else the author chooses.

2017-06-20 10:19 UTC, rohanchandra commented
Oh cool I didn't know about that. Feel free to make a separate PR for that.

2017-07-09 22:27 UTC, rohanchandra commented
@divayprakash, did you want to write the docs for this feature? If not, I can write them then merge the feature in.

2017-07-13 13:54 UTC, divayprakash commented
@rohanchandra Hey! Sorry about the late response but I got caught up in my brother's wedding and then campus placements. I'd be glad to finish up the docs for this feature but it might take me some time. I hope that's okay.

2017-07-13 23:58 UTC, rohanchandra commented
@divayprakash No worries, I'll leave it with you 😄

2017-08-31 11:16 UTC, divayprakash commented
@rohanchandra I'm extremely sorry for the delay but I won't be able to write the docs after all. If you could go ahead and finish that up then I'll also push the code concerning categories. Cheers!

2017-08-31 11:28 UTC, rohanchandra commented
@divayprakash No problem, I'll write up the docs soon.

Just to confirm the things to note are:

* Add tags to a post by adding `tags: [tag_name]` to the Markdown
* Disable the tag index listing by adding `exclude: [tags.html]` to `_config.yml`

Is there anything else you think I should include?

2017-09-17 05:07 UTC, merged

2017-09-17 11:26 UTC, rohanchandra commented
Thanks again @divayprakash, I've merged in the changes. Do you know if there's a way to get `tags.html` working with Jekyll theme gems?

2017-09-26 17:44 UTC, divayprakash commented
@rohanchandra I have no clue about that but I'll let you know if I find something.

2017-09-27 04:06 UTC, rohanchandra commented
@divayprakash Have a read of https://jekyllrb.com/docs/themes/. In summary, Jekyll themes are moving to a model of gem-based themes, where users can install the theme adding the theme to their `Gemfile`.

I've documented some of the current issues with the Type gem theme in #59, one of which is getting tags to work once you've installed the gem-based theme.